export { initializeFastTextModule } from '../helpers/models/browser'
export { getFastTextModule } from '../helpers/models'
export { FastText } from '../FastText'
export { FastTextModel } from '../FastTextModel'
export { LanguageIdentifyModel } from '../tools/language-detect/browser'
